### ISSUE TITLE
Login Async with scope openid profile is not working

### ISSUE THREAD

**Issue by alexistheriault** [auth0/Auth0.WindowsPhone#16]
Hi,

I would like to use 'open id profile' to login. When doing so after entering my credentials I get a white screen with the following text: 'OK'.

I would like to know if there is a way of doing that with this nuget package?

Thank you

**Comment by dschenkelman** [comment]
That is weird. Could you provide a code snippet that reproduces the issue? The value you must pass as `scope` is `"openid profile"` (I notice you wrote it with a space between "open" and "id"). Do not include your client secret in the snippet, instead provide your tenant name and client/app name so I can look it up.

**Comment by alexistheriault** [comment]
Here is the code I am using:

            Auth0Client auth0Client = new Auth0Client("wonderware.auth0.com", "clientId");

            var user = await auth0Client.LoginAsync("wwonlineint2.onmicrosoft.com", "openid profile");

**Comment by dschenkelman** [comment]
Could you connect to our chat: http://chat.auth0.com please?

I need the `clientId` value  and a pair of credentials to use for the test so it is better if you send those to me via a private message in the chat.

**Comment by dschenkelman** [comment]
Found the cause. Known limitation for IE URL length. If using `"openid"` or `"openid email"` it works. Already discussed via chat.

**Comment by alexistheriault** [comment]
Thanks for your help it is working.
